### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by OPcoolman** [Gsnipe1blookethacks/blookethack#18]

**Comment by 3kh0** [comment]
> Hi

we all know that you stole the blooket hacks, stop distributing them

**Comment by smintf** [comment]
Nice bs in your [`README.md`](https://raw.githubusercontent.com/Gsnipe1blookethacks/blookethack/main/README.md)

**Comment by Gsnipe1blookethacks** [comment]
Name one thing that isn't true

**Comment by smintf** [comment]
`Hey guys, this guy claimed that I stole his code and threatened me so I took down the codes. I will make new ones soon but for now try emailing me for special access to my private menu repo at [grahamsnipes1@gmail.com](mailto:grahamsnipes1@gmail.com). I'm kinda upset rn because I spent more than 3 weeks on these codes. I tried to reason with him but he said he would file a lawsuit against me. I had no choice because I did not want to deal with that I am going to start from scratch abd make new codes in the coming weeks. Thanks so much for the support some of you guys have shown, it meant the world to me and I will continue to try to make the best codes possible:( Its been a really fun journey with this project and I hope to re-join the blooket hack game soon. I just wanted to give you guys one last thanks for evrything you have shown to this repo.`

It's entirely false for gods sake you did nothing but change the credits that `window.alert` displays.

**Comment by smintf** [comment]
You didn't even bother changing the links embedded in HTML menu.

**Comment by Gsnipe1blookethacks** [comment]
You game mode code is an instant ban right now and mine wasn't so I did actually edit and fix the code every day

**Comment by Gsnipe1blookethacks** [comment]
You're right because I didn't copy it

**Comment by Gsnipe1blookethacks** [comment]
Plus I took it down can you just move on

**Comment by smintf** [comment]
> You game mode code is an instant ban right now and mine wasn't so I did actually edit and fix the code every day

`Instant Ban` being simply getting kicked out off the game.

**Comment by Gsnipe1blookethacks** [comment]
I never even said your name

**Comment by Gsnipe1blookethacks** [comment]
It also bans you

**Comment by smintf** [comment]
> You're right because I didn't copy it

First you aren't even supposed to even modify a line of code unless i explicitly invited you as a collaborator on the [original repo](https://github.com/Blooketware/BlooketUI) due to the NoDerivatives clause.

**Comment by Gsnipe1blookethacks** [comment]
I didn't mod any code I made a code

**Comment by smintf** [comment]
> It also bans you

Whether it does or not isn't my problem as much as you falsifying events and breaking licenses.

**Comment by Gsnipe1blookethacks** [comment]
Chill out the repo is down you got what you wanted now have a good night

**Comment by Snowflake-Coder-H2o** [comment]
@smintf For real leave him alone. You wanted him to take HIS code down and he did. Why are you still here? Like you must love drama.

**Comment by Gsnipe1blookethacks** [comment]
Actually I updated the code every day and fixed the codes that didn't work

**Comment by 3kh0** [comment]
We both know that that is a lie, there is no point in trying anymore.

**Comment by Everest187** [comment]
> @smintf For real leave him alone. You wanted him to take HIS code down and he did. Why are you still here? Like you must love drama.

> I didn't mod any code I made a code

Cope harder, "claimed that I stole his code" you're a skid and not admitting to it, sending out false information, clearly you "modified" the code without permission and then claimed you created the entire Hack. You didn't bother changing any of the UI   and you're still distributing the code.

**Comment by Snowflake-Coder-H2o** [comment]
@smintf Wait what?

**Comment by Snowflake-Coder-H2o** [comment]
@smintf I thought he coded it all.

**Comment by Snowflake-Coder-H2o** [comment]
@smintf mb.

**Comment by 3kh0** [comment]
> @smintf I thought he coded it all.

Nope! He just copied it from here: https://github.com/Blooketware/BlooketUI

**Comment by Gsnipe1blookethacks** [comment]
Snow I did code it. My code is the one that works his code is the one that gets you baned

**Comment by 3kh0** [comment]
@Gsnipe1blookethacks stop putting up the bullshit

**Comment by Everest187** [comment]
> Snow I did code it. My code is the one that works his code is the one that gets you baned

Bro you're skidding and claiming you made the entire thing, first of all taking the code and modifying it is against the rules in the first place 2ndly you didn't edit shit

**Comment by Snowflake-Coder-H2o** [comment]
@smintf damn

**Comment by Gsnipe1blookethacks** [comment]
@smintf you gotta take down that autolingo you know that I made it.
